# Generated by Django 3.0.3 on 2020-07-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_commentfavorrecord_commentrecord_newsdetails_newsfavorrecord_viewrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
