# Generated by Django 3.0.3 on 2020-08-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auction_auctionitem_auctionitemdetail_auctionitemimage_bidrecord_browserecord_depositrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='auctionitemdetail',
            name='item',
        ),
        migrations.RemoveField(
            model_name='auctionitemimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='bidrecord',
            name='item',
        ),
        migrations.RemoveField(
            model_name='bidrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='browserecord',
            name='item',
        ),
        migrations.RemoveField(
            model_name='browserecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='depositrecord',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='depositrecord',
            name='item',
        ),
        migrations.RemoveField(
            model_name='depositrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='AuctionItem',
        ),
        migrations.DeleteModel(
            name='AuctionItemDetail',
        ),
        migrations.DeleteModel(
            name='AuctionItemImage',
        ),
        migrations.DeleteModel(
            name='BidRecord',
        ),
        migrations.DeleteModel(
            name='BrowseRecord',
        ),
        migrations.DeleteModel(
            name='DepositRecord',
        ),
    ]
