# Generated by Django 3.0.3 on 2020-08-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auction_auctionitem_auctionitemdetail_auctionitemimage_bidrecord_browserecord_depositrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.PositiveIntegerField(default=1000, verbose_name='余额'),
        ),
    ]
